version: '3.6'
services:
    rpc:
        container_name: rpc
        environment:
            RPC_PORT: "7777"
            RPC_IP: "127.0.0.1"
            RPC_THREADS: "20"
            DATADIR: "/root/.config/whiteblock/"
        image: "gcr.io/wb-genesis/rpc:$WB_BRANCH"
        network_mode: "host"
        ports: 
            - "7070:7070"
        restart: always
        ulimits:
            nofile: 20000
        volumes:
            - /home/appo/.config/whiteblock/rpc/:/root/.config/whiteblock/
    genesis:
        container_name: genesis
        image: "gcr.io/wb-genesis/genesis:$WB_BRANCH"
        network_mode: "host"
        environment:
            LISTEN: "127.0.0.1:8000"
            SSH_KEY: "/root/.ssh/id_ed25519"
            RSA_KEY: "/root/.ssh/id_ed25519"
            SSH_USER: "appo"
            RSA_USER: "appo"
            IP_PREFIX: "10"
            SERVER_BITS: "8"
            CLUSTER_BITS: "12"
            NODE_BITS: "4"
            SERVICE_NETWORK: "172.30.0.1/16"
            SERVICE_NETWORK_NAME: "wb_builtin_services"
            NODE_PREFIX: "whiteblock-node"
            NODE_NETWORK_PREFIX: "wb_vlan_"
            SERVICE_PREFIX: "wb_service"
            NODES_PUBLIC_KEY: /keys/id.master.pub
            NODES_PRIVATE_KEY: /keys/id.master
            HANDLE_NODES_SSH_KEYS: 1
            MAX_COMMAND_OUTPUT_LOG_SIZE: "200"
            VERBOSITY: WARN
            API_ENDPOINT: "$API_URL"
        env_file:
            - biome.env
        ports: 
            - "8000:8000"
        restart: always
        volumes: 
            - /home/appo/.ssh:/root/.ssh
            - /home/appo/.config/whiteblock/:/root/.config/whiteblock/
            - /home/master-secrets/:/keys/
    record:
        container_name: record
        depends_on:
            - rpc
        environment:
            RPC: "127.0.0.1:7777"
            LOG_DIRECTORY: "/"
            UPDATE_INTERVAL: "500"
            LISTEN: "127.0.0.1:6060"
            MAX_BLOCKS_TO_LOAD: "40"
            MAX_CONNECTIONS: "50"
            DATADIR: "/root/.config/whiteblock/"
            VERBOSITY: WARN
            API_URL: "$API_URL"
        image: "gcr.io/wb-genesis/bitbucket.org/whiteblockio/record:$WB_BRANCH"
        network_mode: "host"
        ports:
            - "6060:6060"
        restart: always
        volumes:
            - /home/appo/.config/whiteblock/record/:/root/.config/whiteblock/

    record2:
        container_name: record2
        depends_on:
            - rpc
        environment:
            RPC: "127.0.0.1:7777"
            LOG_DIRECTORY: "/"
            UPDATE_INTERVAL: "500"
            LISTEN: "127.0.0.1:6061"
            MAX_BLOCKS_TO_LOAD: "40"
            MAX_CONNECTIONS: "2"
            DATADIR: "/root/.config/whiteblock/"
            VERBOSITY: WARN
            TIMEOUT_ON_FAIL: "2000"
            MAX_API_ATTEMPTS: "50"
            API_URL: "$API_URL"
        image: "gcr.io/wb-genesis/record:$WB_BRANCH"
        network_mode: "host"
        ports:
            - "6060:6060"
        restart: always
        volumes:
            - /home/appo/.config/whiteblock/record2/:/root/.config/whiteblock/
    router:
        container_name: router
        depends_on:
            - rpc
            - genesis
            - record
        image: "gcr.io/wb-genesis/router:$WB_BRANCH"
        network_mode: "host"
        environment:
            GENESIS: "127.0.0.1:8000"
            RPC: "127.0.0.1:7777"
            LISTEN: "127.0.0.1:5000"
            LISTEN_TLS: "0.0.0.0:5001"
            UPDATE_INTERVAL: "1000"
            RECORD: "127.0.0.1:6060"
            ROUTER_USE_TLS: 1
            KEY_PATH: "/etc/secrets/router.key"
            CERT_PATH: "/etc/secrets/router.crt"
            VERBOSITY: WARN
            API_URL: "$API_URL"
            WB_TOKEN_ISSUER: "$WB_TOKEN_ISSUER"
        env_file:
            - biome.env
        ports:
            - "5000:5000"
        restart: always
        volumes:
            - /etc/secrets:/etc/secrets
