version: '3.6'
services:
    genesis:
        container_name: genesis
        image: "gcr.io/whiteblock/genesis:$WB_BRANCH"
        network_mode: "host"
        environment:
            LISTEN: "127.0.0.1:8000"
            SSH_KEY: "/root/.ssh/id_ed25519"
            RSA_KEY: "/root/.ssh/id_ed25519"
            SSH_USER: "whiteblock"
            RSA_USER: "whiteblock"
            IP_PREFIX: "10"
            SERVER_BITS: "8"
            CLUSTER_BITS: "12"
            NODE_BITS: "4"
            SERVICE_NETWORK: "172.30.0.1/16"
            SERVICE_NETWORK_NAME: "wb_builtin_services"
            NODE_PREFIX: "whiteblock-node"
            NODE_NETWORK_PREFIX: "wb_vlan_"
            SERVICE_PREFIX: "wb_service"
            NODES_PUBLIC_KEY: /keys/id_ed25519.pub
            NODES_PRIVATE_KEY: /keys/id_ed25519
            HANDLE_NODES_SSH_KEYS: 1
            MAX_COMMAND_OUTPUT_LOG_SIZE: "200"
            VERBOSITY: WARN
            ENABLE_DOCKER_LOGGING: "true"
        env_file:
            - biome.env
        ports: 
            - "8000:8000"
        restart: always
        volumes: 
            - /home/whiteblock/.ssh:/root/.ssh
            - /home/whiteblock/.config/whiteblock/:/root/.config/whiteblock/
            - /home/whiteblock/.ssh/:/keys/
